### ISSUE TITLE
单选和多选按钮在ios上点击延迟

### ISSUE THREAD

**Issue by jieyou** [junewinds/jmui#2]
如题,直接用ios设备访问 http://junewinds.github.io/jmui/kitchensink/ios/index.html 
可能是click自带的300ms左右延迟导致的,但对用户体验造成影响,请考虑解决一下?

**Comment by choujimmy** [comment]
是的，就是onClick的300毫秒问题。
我在设计整个组件的时候也考虑过引入react-tap-event-plugin组件，然后所有的组件内部映射onClick和onTouchTap事件来劫持应用程序传输过来的onClick事件，在组件内部使用onTouchTap去响应。但是后来我放弃了，因为这样的话在应用端很容易产生Ghost Click（点透），就算是使用react-tap-event-plugin中的shouldRejectClick也很难适用应用端的各种情况。
况且，在安卓手机上，现在大部分的webview设置<meta name="viewport" content="width=device-width">后已经可以消除300ms的延时问题了。
所以，如果是300ms很难接受的话我更建议fork这个project，一个批量把onClick替换成onTouchTap，由使用者自己决定。

**Comment by jieyou** [comment]
感谢回复.
我们考虑自行fork看看
如果能确实解决点透问题,我再提PR
