### ISSUE TITLE
可滚动页面嵌套选择器，会有选择器无法滚动的情况

### ISSUE THREAD

**Issue by jiew** [junewinds/jmui#3]
今天刚刚发现 jmui 这个库，感觉非常适合我们的新项目，特别感谢开发者。但发现个问题，在微信扫二维码使用后，发现『选择器』这个类别中，无论是从下方弹出的选择器还是内联选择器，都无法滚动，从下方弹出的选择器在手势划动时，底层的页面会滚动但是选择器不动，内联滚动器也是类似的问题，请问这个怎么解决呢？多谢！

**Comment by choujimmy** [comment]
没做滚动...

**Comment by jiew** [comment]
哦我还以为是和 iOS 上的滚轮一样的操作方式，抱歉~

**Comment by choujimmy** [comment]
有两个原因这里没做滑动的处理：
- 因为安卓版本的微信内左滑手势是关闭浏览器，所以我整个ui内都没有任何滑动的处理，如果要用的话建议fork来自行处理；
- 这个picker组件从产品的角度上来说其实是不太适合多项内容的选择上的，选个性别啥的还可以，选个省下面的市就很麻烦，就算有滑动也很麻烦，所以我一般都是多项目选择的时候单开页面用list或者radio
